version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5484:5432
    networks:
      - net
    restart: unless-stopped
    container_name: db

  elasticsearch:
    image: elasticsearch:7.17.24
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - net
    restart: unless-stopped
    container_name: elasticsearch

  app:
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      - db
      - elasticsearch
    networks:
      - net
    restart: unless-stopped
    container_name: app

networks:
  net:
    driver: bridge

volumes:
  postgres_data:
  esdata: